# Generated by Django 3.1.13 on 2021-12-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_plant.png', null=True, upload_to='images/'),
        ),
    ]
