# Generated by Django 3.1.13 on 2021-12-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20211209_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_plant.png', upload_to='images/'),
        ),
    ]
